token: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
server: "http://localhost:8008"
mautrix_telegram_db: "dbname=mautrixtelegram"
irc:
    ircnet:
        bridge_server: "irc.snt.utwente.nl"
        room_alias_format: "#_ircnet_.+:irc.snt.utwente.nl"
        appservice_user: "@ircnet:irc.snt.utwente.nl"
    freenode:
        bridge_server: "matrix.org"
        room_alias_format: "#freenode_.+:matrix.org"
        appservice_user: "@appservice-irc:matrix.org"
